exports.up = knex => knex.schema.createTable('products', table => {
  table.increments('id')
  table.string('namePartVehicle').notNullable()
  table.integer('user_id').references('users.id').notNullable().onDelete('CASCADE')
  table.string('brand').notNullable()
  table.decimal('purchasePrice').notNullable()
  table.decimal('marketValue').notNullable()
  table.string('codePart').notNullable()
  table.string('amount').notNullable()
  table.string('barCode').notNullable()
  table.string('category').notNullable()
  table.string('note').notNullable()
  table.timestamp('created_at').defaultTo(knex.fn.now())
  table.timestamp('updated_at').defaultTo(knex.fn.now())
}) 

exports.down = knex => knex.schema.dropTable('products')