exports.seed = knex => {
  return knex('parts_brand').del()
    .then(function () {
      return knex('parts_brand').insert([
        { title: 'ATE' },
        { title: 'Automortex' },
        { title: 'Axios' },
        { title: 'Bosch' },
        { title: 'Cofap' },
        { title: 'Continental' },
        { title: 'Corven' },
        { title: 'Dayco' },
        { title: 'Dayton' },
        { title: 'FAG' },
        { title: 'FORD' },
        { title: 'FRAM' },
        { title: 'FRAS-LE' },
        { title: 'GM' },
        { title: 'Hipper Freios' },
        { title: 'INA' },
        { title: 'Lubrificantes - Lubrax' },
        { title: 'Magneti Marelli' },
        { title: 'MDS' },
        { title: 'NKG' },
        { title: 'Orbi Química' },
        { title: 'Petronas' },
        { title: 'Philips' },
        { title: 'Radiex' },
        { title: 'Sabó' },
        { title: 'Selenia' },
        { title: 'SKF' },
        { title: 'SYL' },
        { title: 'Takao' },
        { title: 'Tecfil' },
        { title: 'Trali' },
        { title: 'TRW' },
        { title: 'UNI' },
        { title: 'VARGA' },
        { title: 'Volkswagen' },
        { title: 'Weber' },
        { title: 'Wisa' },
      ]);
    });
};